# MongoDB Atlas
#spring.data.mongodb.uri=mongodb+srv://saov6000_db_user:s2fr34g4op@cluster0.lpe4ybi.mongodb.net/playlist?retryWrites=true&w=majority
#spring.data.mongodb.database=playlist

#server.port=8080

#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG